import type { Produto } from "./types";

export const categorias = [
  { id: "refrigerante", label: "Refrigerantes" },
  { id: "alcool", label: "Bebidas Alcoólicas" },
  { id: "salgadinho", label: "Salgadinhos" },
  { id: "tabacaria", label: "Tabacaria" },
] as const;

export const produtos: Produto[] = [
  {
    id: "1",
    nome: "Coca-Cola Lata",
    preco: 4.5,
    imagem: "/produtos/refrigerante-1.png",
    categoria: "refrigerante",
    subcategoria: "Cola",
    volume: "350ml",
    origem: "Brasil",
    descricao: "Refrigerante clássico sabor cola.",
    avaliacao: 4.9,
    review: "Gelada é perfeita.",
    autorReview: "Lucas",
  },
  {
    id: "2",
    nome: "Guaraná Antarctica",
    preco: 4.2,
    imagem: "/produtos/refrigerante-2.png",
    categoria: "refrigerante",
    subcategoria: "Guaraná",
    volume: "350ml",
    origem: "Brasil",
    descricao: "Refrigerante brasileiro sabor guaraná.",
    avaliacao: 4.8,
    review: "Combina com qualquer lanche.",
    autorReview: "Ana",
  },
  {
    id: "3",
    nome: "Fanta Laranja",
    preco: 4.0,
    imagem: "/produtos/refrigerante-3.png",
    categoria: "refrigerante",
    subcategoria: "Laranja",
    volume: "350ml",
    origem: "Brasil",
    descricao: "Refrigerante sabor laranja refrescante.",
    avaliacao: 4.5,
    review: "Doce na medida certa.",
    autorReview: "Carlos",
  },
  {
    id: "4",
    nome: "Heineken Long Neck",
    preco: 8.5,
    imagem: "/produtos/alcool-1.png",
    categoria: "alcool",
    subcategoria: "Cerveja",
    volume: "330ml",
    teorAlcool: "5%",
    origem: "Holanda",
    descricao: "Cerveja premium refrescante.",
    avaliacao: 4.7,
    review: "Uma das melhores cervejas.",
    autorReview: "Pedro",
  },
  {
    id: "5",
    nome: "Skol Lata",
    preco: 4.8,
    imagem: "/produtos/alcool-2.png",
    categoria: "alcool",
    subcategoria: "Cerveja",
    volume: "350ml",
    teorAlcool: "4.7%",
    origem: "Brasil",
    descricao: "Cerveja leve e refrescante.",
    avaliacao: 4.2,
    review: "Boa para o churrasco.",
    autorReview: "Marcos",
  },
  {
    id: "6",
    nome: "Smirnoff Ice",
    preco: 9.9,
    imagem: "/produtos/alcool-3.png",
    categoria: "alcool",
    subcategoria: "Ice",
    volume: "275ml",
    teorAlcool: "5%",
    origem: "Rússia",
    descricao: "Bebida alcoólica sabor limão.",
    avaliacao: 4.4,
    review: "Bem refrescante.",
    autorReview: "Julia",
  },
  {
    id: "7",
    nome: "Doritos Nacho",
    preco: 12.5,
    imagem: "/produtos/salgadinho-1.png",
    categoria: "salgadinho",
    subcategoria: "Milho",
    volume: "140g",
    origem: "Brasil",
    descricao: "Salgadinho de milho sabor queijo nacho.",
    avaliacao: 4.8,
    review: "Viciante!",
    autorReview: "Rafael",
  },
  {
    id: "8",
    nome: "Cheetos Requeijão",
    preco: 9.9,
    imagem: "/produtos/salgadinho-2.png",
    categoria: "salgadinho",
    subcategoria: "Milho",
    volume: "120g",
    origem: "Brasil",
    descricao: "Salgadinho crocante sabor requeijão.",
    avaliacao: 4.6,
    review: "Muito saboroso.",
    autorReview: "Fernanda",
  },
  {
    id: "9",
    nome: "Batata Pringles Original",
    preco: 15.9,
    imagem: "/produtos/salgadinho-3.png",
    categoria: "salgadinho",
    subcategoria: "Batata",
    volume: "104g",
    origem: "Estados Unidos",
    descricao: "Batata chips crocante clássica.",
    avaliacao: 4.9,
    review: "Difícil parar de comer.",
    autorReview: "Gustavo",
  },
  {
    id: "10",
    nome: "Seda Papel King Size",
    preco: 6.0,
    imagem: "/produtos/tabacaria-1.png",
    categoria: "tabacaria",
    subcategoria: "Seda",
    volume: "33 folhas",
    origem: "Brasil",
    descricao: "Papel para enrolar cigarros.",
    avaliacao: 4.5,
    review: "Queima uniforme.",
    autorReview: "Bruno",
  },
  {
    id: "11",
    nome: "Isqueiro Bic",
    preco: 5.5,
    imagem: "/produtos/tabacaria-2.png",
    categoria: "tabacaria",
    subcategoria: "Isqueiro",
    volume: "Unidade",
    origem: "França",
    descricao: "Isqueiro clássico descartável.",
    avaliacao: 4.7,
    review: "Dura bastante.",
    autorReview: "Leo",
  },
  {
    id: "12",
    nome: "Filtro para Cigarro",
    preco: 7.9,
    imagem: "/produtos/tabacaria-3.png",
    categoria: "tabacaria",
    subcategoria: "Filtro",
    volume: "100 unidades",
    origem: "Brasil",
    descricao: "Filtros para cigarro enrolado.",
    avaliacao: 4.4,
    review: "Boa qualidade.",
    autorReview: "Paulo",
  },
];

export function getProdutoPorId(id: string): Produto | undefined {
  return produtos.find((p) => p.id === id);
}

export function getProdutosPorCategoria(categoria: string): Produto[] {
  if (!categoria) return produtos;
  return produtos.filter((p) => p.categoria === categoria);
}

export function getSubcategorias(categoria: string): string[] {
  const filtrados = produtos.filter((p) => p.categoria === categoria);
  const sub = [
    ...new Set(filtrados.map((p) => p.subcategoria).filter(Boolean)),
  ] as string[];
  return sub;
}
